"""empty message

Revision ID: 4f411cd30537
Revises: e45dbeeb4cc6
Create Date: 2023-05-05 03:24:32.287220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f411cd30537'
down_revision = 'e45dbeeb4cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isFastrack', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isFastrack')

    # ### end Alembic commands ###
