"""empty message

Revision ID: e45dbeeb4cc6
Revises: 
Create Date: 2023-05-05 01:05:50.529407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45dbeeb4cc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_conditions', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('allergies', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('medications', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('vaccine_history', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('family_history', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('surgical_history', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('lifestyle_habits', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lifestyle_habits')
        batch_op.drop_column('surgical_history')
        batch_op.drop_column('family_history')
        batch_op.drop_column('vaccine_history')
        batch_op.drop_column('medications')
        batch_op.drop_column('allergies')
        batch_op.drop_column('medical_conditions')

    # ### end Alembic commands ###
